import React from "react";
import { Link, useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";
import "./report.css";

export default function Report() {
  const navigate = useNavigate();

  const isLoggedIn = !!localStorage.getItem("zerotrace_auth");

  const requireLogin = (action) => {
    if (!isLoggedIn) {
      sessionStorage.setItem("zerotrace_return", "/report");
      navigate("/auth");
      return;
    }

    action();
  };

  const report = {
    agent: "TRASY Demo Agent",
    evaluationId: "ZT-" + Date.now().toString().slice(-6),
    score: 87,
    threat: "LOW",
    tests: 56,
    dimensions: 10,
    scenarios: 24,
    status: "COMPLETED"
  };

  const downloadPDF = () => {
    const pdf = new jsPDF();

    pdf.setFillColor(9, 13, 32);
    pdf.rect(0, 0, 210, 297, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(26);
    pdf.text("ZEROTRACE", 20, 25);

    pdf.setFontSize(11);
    pdf.setTextColor(100, 220, 255);
    pdf.text("AI RELIABILITY EVALUATION REPORT", 20, 34);

    pdf.setTextColor(220, 225, 245);
    pdf.setFontSize(12);

    pdf.text("Evaluation ID: " + report.evaluationId, 20, 52);
    pdf.text("Agent: " + report.agent, 20, 61);
    pdf.text("Status: " + report.status, 20, 70);

    pdf.setFontSize(20);
    pdf.setTextColor(170, 110, 255);
    pdf.text("Reliability Score", 20, 92);

    pdf.setFontSize(42);
    pdf.setTextColor(255, 255, 255);
    pdf.text(report.score + "%", 20, 112);

    pdf.setFontSize(13);
    pdf.setTextColor(100, 220, 255);
    pdf.text("Threat Level: " + report.threat, 20, 125);

    pdf.setTextColor(220, 225, 245);
    pdf.setFontSize(14);
    pdf.text("Evaluation Summary", 20, 150);

    pdf.setFontSize(11);
    pdf.text("Total Security Checks: " + report.tests, 25, 163);
    pdf.text("Behavioral Dimensions: " + report.dimensions, 25, 173);
    pdf.text("Adversarial Scenarios: " + report.scenarios, 25, 183);

    pdf.setFontSize(14);
    pdf.text("Assessment", 20, 207);

    pdf.setFontSize(11);
    const assessment =
      "The evaluated AI agent demonstrates strong overall reliability. " +
      "TRASY completed adversarial behavioral checks and identified no " +
      "critical reliability failures during this evaluation cycle.";

    const lines = pdf.splitTextToSize(assessment, 165);
    pdf.text(lines, 20, 220);

    pdf.setFontSize(10);
    pdf.setTextColor(120, 130, 160);
    pdf.text("Generated by ZeroTrace / TRASY Autonomous AI Reliability Engine", 20, 275);
    pdf.text("Quantum University, Roorkee", 20, 283);
    pdf.text("MIT License", 20, 291);

    pdf.save("ZeroTrace-AI-Evaluation-Report.pdf");
  };

  return (
    <main className="zt-report">

      <section className="report-header">
        <div>
          <span className="report-tag">ZEROTRACE / TRASY / FINAL REPORT</span>
          <h1>AI Evaluation <span>Report.</span></h1>
          <p>
            Autonomous adversarial evaluation and reliability analysis
            generated by the TRASY evaluation engine.
          </p>
        </div>

        <button className="download-btn" onClick={() => requireLogin(downloadPDF)}>
          ↓ DOWNLOAD PDF
        </button>
      </section>

      <section className="report-score">

        <div className="score-main">
          <small>RELIABILITY SCORE</small>
          <strong>{report.score}%</strong>
          <span>STRONG RELIABILITY</span>
        </div>

        <div className="score-info">
          <div>
            <small>AGENT</small>
            <b>{report.agent}</b>
          </div>

          <div>
            <small>THREAT LEVEL</small>
            <b className="green">{report.threat}</b>
          </div>

          <div>
            <small>STATUS</small>
            <b className="cyan">{report.status}</b>
          </div>

          <div>
            <small>EVALUATION ID</small>
            <b>{report.evaluationId}</b>
          </div>
        </div>

      </section>

      <section className="report-grid">

        <article>
          <small>EVALUATION COVERAGE</small>
          <h2>56</h2>
          <p>Security Checks</p>
        </article>

        <article>
          <small>BEHAVIORAL ANALYSIS</small>
          <h2>10</h2>
          <p>Dimensions Tested</p>
        </article>

        <article>
          <small>ADVERSARIAL TESTING</small>
          <h2>24</h2>
          <p>Scenarios Executed</p>
        </article>

      </section>

      <section className="report-section">

        <span>01 / ASSESSMENT</span>
        <h2>Evaluation Summary</h2>

        <p>
          The evaluated AI agent demonstrates strong overall reliability.
          TRASY performed adversarial testing across multiple behavioral
          dimensions to identify unsafe, inconsistent or unreliable
          responses.
        </p>

        <div className="finding success">
          <b>✓ SYSTEM RELIABILITY</b>
          <span>No critical reliability failure detected.</span>
        </div>

        <div className="finding">
          <b>◈ BEHAVIORAL CONSISTENCY</b>
          <span>Agent remained stable across evaluated scenarios.</span>
        </div>

        <div className="finding">
          <b>◉ ADVERSARIAL RESILIENCE</b>
          <span>Agent successfully handled the majority of stress tests.</span>
        </div>

      </section>

      <section className="report-actions">
        <button onClick={() => requireLogin(downloadPDF)} className="download-btn">
          DOWNLOAD COMPLETE REPORT ↓
        </button>

        <Link to="/dashboard">← BACK TO DASHBOARD</Link>
        <Link to="/test-ai">RUN ANOTHER EVALUATION →</Link>
      </section>

    </main>
  );
}

