import React, { useMemo } from "react";
import { Link, useNavigate } from "react-router-dom";
import { isAuthenticated, setReturnUrl } from "../../utils/auth";
import "./report.css";

export default function Report() {
  const navigate = useNavigate();
  const isLoggedIn = isAuthenticated();

  const requireLogin = (action) => {
    if (!isLoggedIn) {
      setReturnUrl("/report");
      navigate("/auth");
      return;
    }
    action();
  };

  const evaluation = useMemo(() => {
    try {
      const saved = sessionStorage.getItem("zerotrace_evaluation");
      return saved ? JSON.parse(saved) : null;
    } catch {
      return null;
    }
  }, []);

  const score = Math.round(evaluation?.reliability_score ?? 87);
  const threat = evaluation?.risk_level || "LOW";
  const evaluationId = evaluation?.evaluation_id || "ZT-LIVE-001";
  const scenarioCount = evaluation?.scenario_results?.length ?? evaluation?.scenarios?.length ?? "unavailable";
  const agreement = evaluation?.evaluator_agreement;
  const failures = evaluation?.failures || [];
  const recommendations = evaluation?.recommendations || [];

  const downloadPDF = () => {
    const pdf = new jsPDF();

    pdf.setFillColor(9, 13, 32);
    pdf.rect(0, 0, 210, 297, "F");

    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(26);
    pdf.text("ZEROTRACE", 20, 25);

    pdf.setFontSize(11);
    pdf.setTextColor(100, 220, 255);
    pdf.text("AI RELIABILITY EVALUATION REPORT", 20, 34);

    pdf.setTextColor(220, 225, 245);
    pdf.setFontSize(12);

    pdf.text("Evaluation ID: " + evaluationId, 20, 52);
    pdf.text("Risk Level: " + threat, 20, 61);
    pdf.text("Scenarios Executed: " + scenarioCount, 20, 70);

    pdf.setFontSize(20);
    pdf.setTextColor(170, 110, 255);
    pdf.text("Reliability Score", 20, 92);

    pdf.setFontSize(42);
    pdf.setTextColor(255, 255, 255);
    pdf.text(score + "%", 20, 112);

    pdf.setFontSize(13);
    pdf.setTextColor(100, 220, 255);
    pdf.text("Threat Classification: " + threat, 20, 125);

    if (agreement && agreement.agreement_score != null) {
      pdf.text(`Evaluator Agreement: ${agreement.agreement_score}% (${agreement.agreement_level})`, 20, 135);
    }

    pdf.setTextColor(220, 225, 245);
    pdf.setFontSize(14);
    pdf.text("Evaluation Summary", 20, 150);

    pdf.setFontSize(11);
    pdf.text("Evaluated Scenarios: " + scenarioCount, 25, 163);
    pdf.text("Core Dimensions Tested: 5", 25, 173);
    pdf.text("Deviations / Failures Found: " + failures.length, 25, 183);

    pdf.setFontSize(14);
    pdf.text("Assessment", 20, 207);

    pdf.setFontSize(11);
    const assessment = failures.length > 0
      ? `Evaluation detected ${failures.length} deviation(s): ${failures.slice(0, 2).join(" ")}`
      : "The evaluated AI agent demonstrates strong overall reliability. TRASY completed adversarial behavioral checks and identified no critical reliability failures.";

    const lines = pdf.splitTextToSize(assessment, 165);
    pdf.text(lines, 20, 220);

    pdf.setFontSize(10);
    pdf.setTextColor(120, 130, 160);
    pdf.text("Generated by ZeroTrace / TRASY Autonomous AI Reliability Engine", 20, 275);
    pdf.text("Quantum University, Roorkee", 20, 283);
    pdf.text("MIT License", 20, 291);

    pdf.save("ZeroTrace-AI-Evaluation-Report.pdf");
  };

  return (
    <main className="zt-report">
      <section className="report-header">
        <div>
          <span className="report-tag">ZEROTRACE / TRASY / FINAL REPORT</span>
          <h1>AI Evaluation <span>Report.</span></h1>
          <p>
            Autonomous adversarial evaluation and reliability analysis
            generated by the TRASY evaluation engine.
          </p>
        </div>

        <button className="download-btn" onClick={() => requireLogin(downloadPDF)}>
          ↓ DOWNLOAD PDF
        </button>
      </section>

      <section className="report-score">
        <div className="score-main">
          <small>RELIABILITY SCORE</small>
          <strong>{score}%</strong>
          <span>{threat === "LOW" ? "STRONG RELIABILITY" : threat === "MEDIUM" ? "MODERATE RELIABILITY" : "ATTENTION REQUIRED"}</span>
        </div>

        <div className="score-info">
          <div>
            <small>THREAT LEVEL</small>
            <b className={threat === "LOW" ? "green" : "red"}>{threat}</b>
          </div>

          <div>
            <small>SCENARIOS RUN</small>
            <b className="cyan">{scenarioCount}</b>
          </div>

          <div>
            <small>EVALUATION ID</small>
            <b>{evaluationId}</b>
          </div>

          <div>
            <small>CONSENSUS AGREEMENT</small>
            <b>{agreement?.agreement_score != null ? `${agreement.agreement_score}% (${agreement.agreement_level})` : "Standard Mode"}</b>
          </div>
        </div>
      </section>

      <section className="report-grid">
        <article>
          <small>EVALUATION COVERAGE</small>
          <h2>56</h2>
          <p>Security Checks Taxonomy</p>
        </article>

        <article>
          <small>CORE METRICS</small>
          <h2>5</h2>
          <p>Evaluated Dimensions</p>
        </article>

        <article>
          <small>ADVERSARIAL SCENARIOS</small>
          <h2>{scenarioCount}</h2>
          <p>Executed Scenarios</p>
        </article>
      </section>

      <section className="report-section">
        <span>01 / ASSESSMENT</span>
        <h2>Evaluation Summary</h2>

        <p>
          TRASY evaluated the target agent across adversarial testing scenarios and multi-evaluator consensus to identify unsafe, inconsistent, or hallucinated responses.
        </p>

        {failures.length > 0 ? (
          failures.slice(0, 3).map((f, idx) => (
            <div className="finding" key={idx}>
              <b>◈ DEVIATION DETECTED</b>
              <span>{f}</span>
            </div>
          ))
        ) : (
          <>
            <div className="finding success">
              <b>✓ SYSTEM RELIABILITY</b>
              <span>No critical reliability failure detected across scenarios.</span>
            </div>
            <div className="finding">
              <b>◈ BEHAVIORAL CONSISTENCY</b>
              <span>Agent responses adhered to task boundaries and constraints.</span>
            </div>
          </>
        )}

        {recommendations.length > 0 && (
          <div className="finding" style={{ borderLeftColor: "#22d3ee" }}>
            <b>◉ ACTIONABLE RECOMMENDATION</b>
            <span>{recommendations[0]}</span>
          </div>
        )}
      </section>

      <section className="report-actions">
        <button onClick={() => requireLogin(downloadPDF)} className="download-btn">
          DOWNLOAD COMPLETE REPORT ↓
        </button>

        <Link to="/dashboard">← BACK TO DASHBOARD</Link>
        <Link to="/test-ai">RUN ANOTHER EVALUATION →</Link>
      </section>
    </main>
  );
}
