import { useState } from "react";
import { Code2, GraduationCap, BriefcaseBusiness, Mail, Send } from "lucide-react";
import "../../styles/contact.css";
const CONTACT_LINKS = { email: "ADD_EMAIL", github: "ADD_GITHUB_URL", linkedin: "ADD_LINKEDIN_URL", university: "ADD_UNIVERSITY_URL" };
const cards = [["Email", Mail, "email"], ["GitHub", Code2, "github"], ["LinkedIn", BriefcaseBusiness, "linkedin"], ["Quantum University", GraduationCap, "university"]];
const faqs = [["What is ZeroTrace?", "An AI reliability and security platform for stress-testing autonomous AI agents."], ["What is TRASY?", "The Autonomous AI Reliability Engine at the core of ZeroTrace."], ["Who built ZeroTrace?", "Parth Goyal, Archi Sharma and Annu Sharma."], ["Where is the team based academically?", "Quantum University, Roorkee."]];
function Contact() {
  const [errors, setErrors] = useState({}); const [submitted, setSubmitted] = useState(false);
  const submit = (event) => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); const next = {}; if (!data.name.trim()) next.name = "Name is required."; if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(data.email)) next.email = "Enter a valid email."; if (!data.subject.trim()) next.subject = "Subject is required."; if (data.message.trim().length < 20) next.message = "Please enter at least 20 characters."; setErrors(next); setSubmitted(Object.keys(next).length === 0); };
  return <div className="contact-page zt-subpage"><section className="zt-page-hero"><span>ZEROTRACE / CONTACT</span><h1>Let&apos;s <em>Connect</em></h1><p>Have a question, collaboration idea, research opportunity or AI reliability challenge?</p></section><section className="contact-cards">{cards.map(([label, Icon, key]) => <article key={key}><Icon /><span>{label}</span><small>{CONTACT_LINKS[key]}</small></article>)}</section><section className="contact-layout"><div><span className="zt-kicker">START A CONVERSATION</span><h2>Bring us your hardest AI reliability question.</h2><p>Share the context and intended use. This demo validates your message locally and is ready to connect to the delivery service you choose.</p></div><form onSubmit={submit} noValidate>{[["name", "Name", "text"], ["email", "Email", "email"], ["subject", "Subject", "text"]].map(([name, label, type]) => <label key={name}>{label}<input name={name} type={type} aria-invalid={Boolean(errors[name])} />{errors[name] && <small>{errors[name]}</small>}</label>)}<label>Message<textarea name="message" rows="6" aria-invalid={Boolean(errors.message)} />{errors.message && <small>{errors.message}</small>}</label><button type="submit">Send Message <Send size={16} /></button>{submitted && <p className="form-success" role="status">Message form ready — connect this form to your backend/email service.</p>}</form></section><section className="faq-section"><span className="zt-kicker">FAQ / QUICK ANSWERS</span><h2>Frequently asked questions</h2><div>{faqs.map(([q, a]) => <details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div></section></div>;
}
export default Contact;
