import { useEffect, useState } from "react";
import { ArrowLeft, Download, LogOut, ShieldCheck, AlertTriangle, Activity, RotateCcw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { jsPDF } from "jspdf";

const dimensions = [
  ["Goal Alignment", 83],
  ["Instruction Following", 89],
  ["Safety", 76],
  ["Tool Reliability", 75],
  ["Reasoning & Decision", 90],
  ["Robustness", 86],
  ["Failure Recovery", 92],
  ["Consistency", 71],
  ["Efficiency", 91],
  ["Reliability & Observability", 80]
];

const failures = [
  ["TR-0042", "Prompt Injection Resistance", "Safety", "HIGH", 54],
  ["TR-0018", "Tool Error Handling", "Tool Reliability", "HIGH", 61],
  ["TR-0031", "Instruction Consistency", "Consistency", "MEDIUM", 71],
  ["TR-0050", "Failure Recovery", "Failure Recovery", "MEDIUM", 78]
];

function FullReport() {
  const navigate = useNavigate();
  const [auth, setAuth] = useState(null);

  const score = 83;

  useEffect(() => {
    const savedAuth = sessionStorage.getItem("zerotrace_auth");

    if (!savedAuth) {
      navigate("/auth");
      return;
    }

    try {
      const parsed = JSON.parse(savedAuth);

      if (!parsed.authenticated) {
        navigate("/auth");
        return;
      }

      setAuth(parsed);
    } catch {
      navigate("/auth");
    }
  }, [navigate]);

  const downloadPDF = () => {
    const pdf = new jsPDF();

    pdf.setFontSize(22);
    pdf.text("ZeroTrace / TRASY", 20, 25);

    pdf.setFontSize(11);
    pdf.text("AI AGENT RELIABILITY REPORT", 20, 34);

    pdf.setFontSize(32);
    pdf.text(`${score}/100`, 20, 55);

    pdf.setFontSize(12);
    pdf.text("Reliability Score", 20, 64);

    pdf.setFontSize(10);
    pdf.text("Evaluation Summary", 20, 82);
    pdf.text("56 checks completed across 10 reliability dimensions.", 20, 90);
    pdf.text("Adversarial evaluation with trace-backed failure analysis.", 20, 98);

    pdf.setFontSize(12);
    pdf.text("Reliability Dimensions", 20, 116);

    let y = 126;

    dimensions.forEach(([name, value]) => {
      pdf.setFontSize(9);
      pdf.text(`${name}: ${value}/100`, 20, y);
      y += 8;
    });

    y += 8;

    pdf.setFontSize(12);
    pdf.text("Observed Failures", 20, y);

    y += 10;

    failures.forEach(([id, name, category, severity, value]) => {
      pdf.setFontSize(9);
      pdf.text(`${id} | ${name} | ${category} | ${severity} | ${value}/100`, 20, y);
      y += 8;
    });

    y += 10;

    pdf.setFontSize(12);
    pdf.text("TRASY Analysis", 20, y);

    y += 9;

    pdf.setFontSize(9);
    pdf.text(
      "The evaluated agent demonstrates strong overall reliability",
      20,
      y
    );

    y += 7;

    pdf.text(
      "but exhibits weaknesses in safety, tool reliability and consistency.",
      20,
      y
    );

    y += 7;

    pdf.text(
      "Further regression testing is recommended before production deployment.",
      20,
      y
    );

    pdf.save("ZeroTrace-TRASY-Reliability-Report.pdf");
  };

  const logout = () => {
    sessionStorage.removeItem("zerotrace_auth");
    navigate("/");
  };

  if (!auth) {
    return null;
  }

  return (
    <div className="full-report-page">

      <header className="full-report-header">

        <button
          className="full-report-back"
          onClick={() => navigate("/report")}
        >
          <ArrowLeft size={15} />
          REPORT PREVIEW
        </button>

        <div className="full-report-brand">
          <div className="full-report-logo">Z</div>
          <strong>ZeroTrace</strong>
        </div>

        <button
          className="logout-button"
          onClick={logout}
        >
          <LogOut size={14} />
          LOG OUT
        </button>

      </header>


      <main className="full-report-main">

        <div className="full-report-kicker">
          TRASY / VERIFIED RELIABILITY REPORT
        </div>

        <div className="full-report-title-row">

          <div>
            <h1>
              Full Evaluation
              <span>Report.</span>
            </h1>

            <p>
              Complete evidence-backed analysis generated by
              TRASY Autonomous AI Evaluation Engine.
            </p>
          </div>

          <button
            className="download-report-button"
            onClick={downloadPDF}
          >
            <Download size={17} />
            DOWNLOAD PDF
          </button>

        </div>


        <section className="verified-banner">

          <ShieldCheck size={18} />

          <div>
            <strong>
              VERIFIED EVALUATION
            </strong>

            <span>
              Identity verified via {auth.method}.
            </span>
          </div>

        </section>


        <section className="full-score-card">

          <div className="score-block">

            <small>
              TRASY RELIABILITY SCORE
            </small>

            <strong>
              {score}
            </strong>

            <span>/100</span>

          </div>


          <div className="score-verdict">

            <small>
              OVERALL VERDICT
            </small>

            <h2>
              Strong, with observed weaknesses
            </h2>

            <p>
              The agent performs well across most dimensions,
              but TRASY identified specific reliability risks
              that should be addressed before production use.
            </p>

          </div>

        </section>


        <section className="report-stat-grid">

          <div>
            <Activity size={16} />
            <small>CHECKS</small>
            <strong>56</strong>
          </div>

          <div>
            <ShieldCheck size={16} />
            <small>DIMENSIONS</small>
            <strong>10</strong>
          </div>

          <div>
            <AlertTriangle size={16} />
            <small>FAILURES</small>
            <strong>4</strong>
          </div>

          <div>
            <RotateCcw size={16} />
            <small>REGRESSION</small>
            <strong>READY</strong>
          </div>

        </section>


        <section className="dimensions-report">

          <div className="section-heading">
            <span>01 / WEIGHTED ANALYSIS</span>
            <h2>Reliability Dimensions</h2>
          </div>

          <div className="dimension-list">

            {dimensions.map(([name, value]) => (

              <div
                className="dimension-row"
                key={name}
              >

                <div className="dimension-name">
                  <span>{name}</span>
                  <strong>{value}</strong>
                </div>

                <div className="dimension-track">
                  <div
                    style={{
                      width: `${value}%`
                    }}
                  />
                </div>

              </div>

            ))}

          </div>

        </section>


        <section className="full-failures">

          <div className="section-heading">
            <span>02 / TRACE-BACKED EVIDENCE</span>
            <h2>Observed Failures</h2>
          </div>


          <div className="full-failure-table">

            <div className="failure-table-head">
              <span>TRACE</span>
              <span>FAILURE</span>
              <span>CATEGORY</span>
              <span>SEVERITY</span>
              <span>SCORE</span>
            </div>

            {failures.map(
              ([id, name, category, severity, value]) => (

                <div
                  className="failure-table-row"
                  key={id}
                >

                  <span>{id}</span>

                  <strong>{name}</strong>

                  <span>{category}</span>

                  <span
                    className={
                      severity === "HIGH"
                        ? "severity-high"
                        : "severity-medium"
                    }
                  >
                    {severity}
                  </span>

                  <span>{value}/100</span>

                </div>

              )
            )}

          </div>

        </section>


        <section className="recommendation-card">

          <span>
            03 / TRASY RECOMMENDATION
          </span>

          <h2>
            Fix the weak signals before deployment.
          </h2>

          <p>
            Prioritize prompt-injection resistance, tool error
            handling and behavioral consistency. Re-run the
            same evaluation after changes to establish a
            regression baseline.
          </p>

        </section>


        <section className="report-actions">

          <button
            onClick={downloadPDF}
          >
            <Download size={16} />
            DOWNLOAD FULL REPORT
          </button>

          <button
            onClick={() => navigate("/")}
          >
            RUN ANOTHER EVALUATION
          </button>

        </section>

      </main>

    </div>
  );
}

export default FullReport;
